//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Requirement
    {
        public string Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModificationTime { get; set; }
        public string CreateUserName { get; set; }
        public string ModificationUserName { get; set; }
        public int SortCode { get; set; }
        public string ParentId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string PK_App_Position_Name { get; set; }
        public string WorkPlace { get; set; }
        public string WorkLimitSex { get; set; }
        public int WorkLimitAgeLow { get; set; }
        public int WorkLimitAgeHigh { get; set; }
        public string EnumWorkLimitDegree { get; set; }
        public string SalaryLow { get; set; }
        public string SalaryHigh { get; set; }
        public string PromiseMoney { get; set; }
        public string ServiceMoney { get; set; }
        public string TotalServiceMoney { get; set; }
        public string PublishDate { get; set; }
        public int TotalHire { get; set; }
        public string Tag { get; set; }
        public string PK_App_Customer_CustomerName { get; set; }
        public string Description { get; set; }
        public string SwitchBtnRecommend { get; set; }
        public string CompanyName { get; set; }
        public string PK_App_Country_Name { get; set; }
        public int TotalYear { get; set; }
        public string TransactProvince { get; set; }
        public int ApplyCount { get; set; }
        public string ServiceTailMoney { get; set; }
        public string SwitchBtnOpen { get; set; }
        public int ClickNumber { get; set; }
        public string PreTaxSalary { get; set; }
        public string WorkHourPerWeek { get; set; }
        public string EnumWorkPermit { get; set; }
    }
}
