//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Customer
    {
        public string Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModificationTime { get; set; }
        public string CreateUserName { get; set; }
        public string ModificationUserName { get; set; }
        public int SortCode { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Record { get; set; }
        public string Info { get; set; }
        public string EnumCustomerLevel { get; set; }
        public string CustomerName { get; set; }
        public string Password { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        public string NickName { get; set; }
        public int Age { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Nation { get; set; }
        public string Introduction { get; set; }
        public string CustomerPhoto { get; set; }
        public string OpenID { get; set; }
        public string BirthDay { get; set; }
        public string BirthPlace { get; set; }
        public string CurrentPlace { get; set; }
        public string WeChatNumber { get; set; }
        public string Cultural { get; set; }
        public string EnumCustomerType { get; set; }
        public string EnumForeignLangGrade { get; set; }
        public string SwitchBtnPassport { get; set; }
        public string AbroadExp { get; set; }
        public string EnumDriverLicence { get; set; }
        public string SwitchBtnRecommend { get; set; }
        public string VideoPath { get; set; }
        public string WordPath { get; set; }
        public string WordName { get; set; }
        public string WordExt { get; set; }
        public string JobIntension { get; set; }
        public string EnglishName { get; set; }
        public string MaritalStatus { get; set; }
        public string PassportNo { get; set; }
        public string Religion { get; set; }
        public string ExpectCountry { get; set; }
        public string SwitchBtnInterview { get; set; }
    }
}
