//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_CustomerJobIntension
    {
        public string Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModificationTime { get; set; }
        public string CreateUserName { get; set; }
        public string ModificationUserName { get; set; }
        public int SortCode { get; set; }
        public string ParentId { get; set; }
        public string PK_App_Customer_CustomerName { get; set; }
        public string EnumPositionType { get; set; }
        public string ExpectSalary { get; set; }
        public string ExpectCountry { get; set; }
        public string Skills { get; set; }
        public string Intention { get; set; }
        public string EnumApplyWay { get; set; }
        public string CurrentPlace { get; set; }
        public string EnumForeignLangGrade { get; set; }
        public string AbroadExp { get; set; }
    }
}
