//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumDictionary
    {
        public int Id { get; set; }
        public Nullable<int> parentId { get; set; }
        public string TableName { get; set; }
        public string ItemName { get; set; }
        public string ItemValue { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModificationTime { get; set; }
        public string CreateUserName { get; set; }
        public string ModificationUserName { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string ItemPhoto { get; set; }
    }
}
