//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMessage
    {
        public string Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModificationTime { get; set; }
        public string CreateUserName { get; set; }
        public string ModificationUserName { get; set; }
        public int SortCode { get; set; }
        public string ParentId { get; set; }
        public string BusinessID { get; set; }
        public string BusinessTable { get; set; }
        public string PK_App_Customer_CustomerName { get; set; }
        public string SwitchBtnRead { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string EnumMessageType { get; set; }
        public string SwitchBtnButton { get; set; }
        public string ShowMessage { get; set; }
        public string WorkerId { get; set; }
    }
}
