//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.App;
using Apps.IDAL.App;
using System;
namespace Apps.DAL.App
{
	public partial class App_ApplyJobRepository:BaseRepository<App_ApplyJob>,IApp_ApplyJobRepository,IDisposable
	{
	    public App_ApplyJobRepository(DBContainer db):base(db)
        {
        
        }
	}
}
