//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.QRTZ;
using Apps.IDAL.QRTZ;
using System;
namespace Apps.DAL.QRTZ
{
	public partial class QRTZ_PAUSED_TRIGGER_GRPSRepository:BaseRepository<QRTZ_PAUSED_TRIGGER_GRPS>,IQRTZ_PAUSED_TRIGGER_GRPSRepository,IDisposable
	{
	    public QRTZ_PAUSED_TRIGGER_GRPSRepository(DBContainer db):base(db)
        {
        
        }
	}
}
