//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.QRTZ;
using Apps.IDAL.QRTZ;
using System;
namespace Apps.DAL.QRTZ
{
	public partial class QRTZ_SIMPROP_TRIGGERSRepository:BaseRepository<QRTZ_SIMPROP_TRIGGERS>,IQRTZ_SIMPROP_TRIGGERSRepository,IDisposable
	{
	    public QRTZ_SIMPROP_TRIGGERSRepository(DBContainer db):base(db)
        {
        
        }
	}
}
