//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.IDAL.App;
using Apps.Models.App;
namespace Apps.BLL.App
{
	public class Virtual_App_ApplyJobRecordBLL
	{
        [Dependency]
        public IApp_ApplyJobRecordRepository m_Rep { get; set; }

		public virtual List<App_ApplyJobRecordModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<App_ApplyJobRecord> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								
								
								|| a.CreateUserName.Contains(queryStr)
								|| a.ModificationUserName.Contains(queryStr)
								
								|| a.ParentId.Contains(queryStr)
								|| a.PK_App_ApplyJob_Id.Contains(queryStr)
								|| a.PK_App_Customer_CustomerName.Contains(queryStr)
								|| a.EnumApplyStatus.Contains(queryStr)
								|| a.Step.Contains(queryStr)
								|| a.Result.Contains(queryStr)
								|| a.Content.Contains(queryStr)
								|| a.HappenDate.Contains(queryStr)
								|| a.ConfigDate.Contains(queryStr)
								|| a.ConfigPlace.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<App_ApplyJobRecordModel> CreateModelList(ref IQueryable<App_ApplyJobRecord> queryData)
        {

            List<App_ApplyJobRecordModel> modelList = (from r in queryData
                                              select new App_ApplyJobRecordModel
                                              {
													Id = r.Id,
													CreateTime = r.CreateTime,
													ModificationTime = r.ModificationTime,
													CreateUserName = r.CreateUserName,
													ModificationUserName = r.ModificationUserName,
													SortCode = r.SortCode,
													ParentId = r.ParentId,
													PK_App_ApplyJob_Id = r.PK_App_ApplyJob_Id,
													PK_App_Customer_CustomerName = r.PK_App_Customer_CustomerName,
													EnumApplyStatus = r.EnumApplyStatus,
													Step = r.Step,
													Result = r.Result,
													Content = r.Content,
													HappenDate = r.HappenDate,
													ConfigDate = r.ConfigDate,
													ConfigPlace = r.ConfigPlace,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, App_ApplyJobRecordModel model)
        {
            try
            {
                App_ApplyJobRecord entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new App_ApplyJobRecord();
               				entity.Id = model.Id;
				entity.CreateTime = model.CreateTime;
				entity.ModificationTime = model.ModificationTime;
				entity.CreateUserName = model.CreateUserName;
				entity.ModificationUserName = model.ModificationUserName;
				entity.SortCode = model.SortCode;
				entity.ParentId = model.ParentId;
				entity.PK_App_ApplyJob_Id = model.PK_App_ApplyJob_Id;
				entity.PK_App_Customer_CustomerName = model.PK_App_Customer_CustomerName;
				entity.EnumApplyStatus = model.EnumApplyStatus;
				entity.Step = model.Step;
				entity.Result = model.Result;
				entity.Content = model.Content;
				entity.HappenDate = model.HappenDate;
				entity.ConfigDate = model.ConfigDate;
				entity.ConfigPlace = model.ConfigPlace;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, App_ApplyJobRecordModel model)
        {
            try
            {
                App_ApplyJobRecord entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.CreateTime = model.CreateTime;
				entity.ModificationTime = model.ModificationTime;
				entity.CreateUserName = model.CreateUserName;
				entity.ModificationUserName = model.ModificationUserName;
				entity.SortCode = model.SortCode;
				entity.ParentId = model.ParentId;
				entity.PK_App_ApplyJob_Id = model.PK_App_ApplyJob_Id;
				entity.PK_App_Customer_CustomerName = model.PK_App_Customer_CustomerName;
				entity.EnumApplyStatus = model.EnumApplyStatus;
				entity.Step = model.Step;
				entity.Result = model.Result;
				entity.Content = model.Content;
				entity.HappenDate = model.HappenDate;
				entity.ConfigDate = model.ConfigDate;
				entity.ConfigPlace = model.ConfigPlace;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual App_ApplyJobRecordModel GetById(string id)
        {
            if (IsExists(id))
            {
                App_ApplyJobRecord entity = m_Rep.GetById(id);
                App_ApplyJobRecordModel model = new App_ApplyJobRecordModel();
                              				model.Id = entity.Id;
				model.CreateTime = entity.CreateTime;
				model.ModificationTime = entity.ModificationTime;
				model.CreateUserName = entity.CreateUserName;
				model.ModificationUserName = entity.ModificationUserName;
				model.SortCode = entity.SortCode;
				model.ParentId = entity.ParentId;
				model.PK_App_ApplyJob_Id = entity.PK_App_ApplyJob_Id;
				model.PK_App_Customer_CustomerName = entity.PK_App_Customer_CustomerName;
				model.EnumApplyStatus = entity.EnumApplyStatus;
				model.Step = entity.Step;
				model.Result = entity.Result;
				model.Content = entity.Content;
				model.HappenDate = entity.HappenDate;
				model.ConfigDate = entity.ConfigDate;
				model.ConfigPlace = entity.ConfigPlace;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
