//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.IDAL.QRTZ;
using Apps.Models.QRTZ;
namespace Apps.BLL.QRTZ
{
	public class Virtual_QRTZ_TRIGGERSBLL
	{
        [Dependency]
        public IQRTZ_TRIGGERSRepository m_Rep { get; set; }

		public virtual List<QRTZ_TRIGGERSModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<QRTZ_TRIGGERS> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.SCHED_NAME.Contains(queryStr)
								|| a.TRIGGER_NAME.Contains(queryStr)
								|| a.TRIGGER_GROUP.Contains(queryStr)
								|| a.JOB_NAME.Contains(queryStr)
								|| a.JOB_GROUP.Contains(queryStr)
								|| a.DESCRIPTION.Contains(queryStr)
								
								
								
								|| a.TRIGGER_STATE.Contains(queryStr)
								|| a.TRIGGER_TYPE.Contains(queryStr)
								
								
								|| a.CALENDAR_NAME.Contains(queryStr)
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<QRTZ_TRIGGERSModel> CreateModelList(ref IQueryable<QRTZ_TRIGGERS> queryData)
        {

            List<QRTZ_TRIGGERSModel> modelList = (from r in queryData
                                              select new QRTZ_TRIGGERSModel
                                              {
													SCHED_NAME = r.SCHED_NAME,
													TRIGGER_NAME = r.TRIGGER_NAME,
													TRIGGER_GROUP = r.TRIGGER_GROUP,
													JOB_NAME = r.JOB_NAME,
													JOB_GROUP = r.JOB_GROUP,
													DESCRIPTION = r.DESCRIPTION,
													NEXT_FIRE_TIME = r.NEXT_FIRE_TIME,
													PREV_FIRE_TIME = r.PREV_FIRE_TIME,
													PRIORITY = r.PRIORITY,
													TRIGGER_STATE = r.TRIGGER_STATE,
													TRIGGER_TYPE = r.TRIGGER_TYPE,
													START_TIME = r.START_TIME,
													END_TIME = r.END_TIME,
													CALENDAR_NAME = r.CALENDAR_NAME,
													MISFIRE_INSTR = r.MISFIRE_INSTR,
													JOB_DATA = r.JOB_DATA,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, QRTZ_TRIGGERSModel model)
        {
            try
            {
                QRTZ_TRIGGERS entity = m_Rep.GetById(model.SCHED_NAME);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new QRTZ_TRIGGERS();
               				entity.SCHED_NAME = model.SCHED_NAME;
				entity.TRIGGER_NAME = model.TRIGGER_NAME;
				entity.TRIGGER_GROUP = model.TRIGGER_GROUP;
				entity.JOB_NAME = model.JOB_NAME;
				entity.JOB_GROUP = model.JOB_GROUP;
				entity.DESCRIPTION = model.DESCRIPTION;
				entity.NEXT_FIRE_TIME = model.NEXT_FIRE_TIME;
				entity.PREV_FIRE_TIME = model.PREV_FIRE_TIME;
				entity.PRIORITY = model.PRIORITY;
				entity.TRIGGER_STATE = model.TRIGGER_STATE;
				entity.TRIGGER_TYPE = model.TRIGGER_TYPE;
				entity.START_TIME = model.START_TIME;
				entity.END_TIME = model.END_TIME;
				entity.CALENDAR_NAME = model.CALENDAR_NAME;
				entity.MISFIRE_INSTR = model.MISFIRE_INSTR;
				entity.JOB_DATA = model.JOB_DATA;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, QRTZ_TRIGGERSModel model)
        {
            try
            {
                QRTZ_TRIGGERS entity = m_Rep.GetById(model.SCHED_NAME);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.SCHED_NAME = model.SCHED_NAME;
				entity.TRIGGER_NAME = model.TRIGGER_NAME;
				entity.TRIGGER_GROUP = model.TRIGGER_GROUP;
				entity.JOB_NAME = model.JOB_NAME;
				entity.JOB_GROUP = model.JOB_GROUP;
				entity.DESCRIPTION = model.DESCRIPTION;
				entity.NEXT_FIRE_TIME = model.NEXT_FIRE_TIME;
				entity.PREV_FIRE_TIME = model.PREV_FIRE_TIME;
				entity.PRIORITY = model.PRIORITY;
				entity.TRIGGER_STATE = model.TRIGGER_STATE;
				entity.TRIGGER_TYPE = model.TRIGGER_TYPE;
				entity.START_TIME = model.START_TIME;
				entity.END_TIME = model.END_TIME;
				entity.CALENDAR_NAME = model.CALENDAR_NAME;
				entity.MISFIRE_INSTR = model.MISFIRE_INSTR;
				entity.JOB_DATA = model.JOB_DATA;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual QRTZ_TRIGGERSModel GetById(string id)
        {
            if (IsExists(id))
            {
                QRTZ_TRIGGERS entity = m_Rep.GetById(id);
                QRTZ_TRIGGERSModel model = new QRTZ_TRIGGERSModel();
                              				model.SCHED_NAME = entity.SCHED_NAME;
				model.TRIGGER_NAME = entity.TRIGGER_NAME;
				model.TRIGGER_GROUP = entity.TRIGGER_GROUP;
				model.JOB_NAME = entity.JOB_NAME;
				model.JOB_GROUP = entity.JOB_GROUP;
				model.DESCRIPTION = entity.DESCRIPTION;
				model.NEXT_FIRE_TIME = entity.NEXT_FIRE_TIME;
				model.PREV_FIRE_TIME = entity.PREV_FIRE_TIME;
				model.PRIORITY = entity.PRIORITY;
				model.TRIGGER_STATE = entity.TRIGGER_STATE;
				model.TRIGGER_TYPE = entity.TRIGGER_TYPE;
				model.START_TIME = entity.START_TIME;
				model.END_TIME = entity.END_TIME;
				model.CALENDAR_NAME = entity.CALENDAR_NAME;
				model.MISFIRE_INSTR = entity.MISFIRE_INSTR;
				model.JOB_DATA = entity.JOB_DATA;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
