//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.IDAL.Sys;
using Apps.Models.Sys;
namespace Apps.BLL.Sys
{
	public class Virtual_sysdiagramsBLL
	{
        [Dependency]
        public IsysdiagramsRepository m_Rep { get; set; }

		public virtual List<sysdiagramsModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<sysdiagrams> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.name.Contains(queryStr)
								
								
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<sysdiagramsModel> CreateModelList(ref IQueryable<sysdiagrams> queryData)
        {

            List<sysdiagramsModel> modelList = (from r in queryData
                                              select new sysdiagramsModel
                                              {
													name = r.name,
													principal_id = r.principal_id,
													diagram_id = r.diagram_id,
													version = r.version,
													definition = r.definition,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, sysdiagramsModel model)
        {
            try
            {
                sysdiagrams entity = m_Rep.GetById(model.name);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new sysdiagrams();
               				entity.name = model.name;
				entity.principal_id = model.principal_id;
				entity.diagram_id = model.diagram_id;
				entity.version = model.version;
				entity.definition = model.definition;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, sysdiagramsModel model)
        {
            try
            {
                sysdiagrams entity = m_Rep.GetById(model.name);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.name = model.name;
				entity.principal_id = model.principal_id;
				entity.diagram_id = model.diagram_id;
				entity.version = model.version;
				entity.definition = model.definition;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual sysdiagramsModel GetById(string id)
        {
            if (IsExists(id))
            {
                sysdiagrams entity = m_Rep.GetById(id);
                sysdiagramsModel model = new sysdiagramsModel();
                              				model.name = entity.name;
				model.principal_id = entity.principal_id;
				model.diagram_id = entity.diagram_id;
				model.version = entity.version;
				model.definition = entity.definition;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
