//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.IDAL.Sys;
using Apps.Models.Sys;
namespace Apps.BLL.Sys
{
	public class Virtual_SysMessageBLL
	{
        [Dependency]
        public ISysMessageRepository m_Rep { get; set; }

		public virtual List<SysMessageModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysMessage> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								
								
								|| a.CreateUserName.Contains(queryStr)
								|| a.ModificationUserName.Contains(queryStr)
								
								|| a.ParentId.Contains(queryStr)
								|| a.BusinessID.Contains(queryStr)
								|| a.BusinessTable.Contains(queryStr)
								|| a.PK_App_Customer_CustomerName.Contains(queryStr)
								|| a.SwitchBtnRead.Contains(queryStr)
								|| a.Title.Contains(queryStr)
								|| a.Content.Contains(queryStr)
								|| a.EnumMessageType.Contains(queryStr)
								|| a.SwitchBtnButton.Contains(queryStr)
								|| a.ShowMessage.Contains(queryStr)
								|| a.WorkerId.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<SysMessageModel> CreateModelList(ref IQueryable<SysMessage> queryData)
        {

            List<SysMessageModel> modelList = (from r in queryData
                                              select new SysMessageModel
                                              {
													Id = r.Id,
													CreateTime = r.CreateTime,
													ModificationTime = r.ModificationTime,
													CreateUserName = r.CreateUserName,
													ModificationUserName = r.ModificationUserName,
													SortCode = r.SortCode,
													ParentId = r.ParentId,
													BusinessID = r.BusinessID,
													BusinessTable = r.BusinessTable,
													PK_App_Customer_CustomerName = r.PK_App_Customer_CustomerName,
													SwitchBtnRead = r.SwitchBtnRead,
													Title = r.Title,
													Content = r.Content,
													EnumMessageType = r.EnumMessageType,
													SwitchBtnButton = r.SwitchBtnButton,
													ShowMessage = r.ShowMessage,
													WorkerId = r.WorkerId,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysMessageModel model)
        {
            try
            {
                SysMessage entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysMessage();
               				entity.Id = model.Id;
				entity.CreateTime = model.CreateTime;
				entity.ModificationTime = model.ModificationTime;
				entity.CreateUserName = model.CreateUserName;
				entity.ModificationUserName = model.ModificationUserName;
				entity.SortCode = model.SortCode;
				entity.ParentId = model.ParentId;
				entity.BusinessID = model.BusinessID;
				entity.BusinessTable = model.BusinessTable;
				entity.PK_App_Customer_CustomerName = model.PK_App_Customer_CustomerName;
				entity.SwitchBtnRead = model.SwitchBtnRead;
				entity.Title = model.Title;
				entity.Content = model.Content;
				entity.EnumMessageType = model.EnumMessageType;
				entity.SwitchBtnButton = model.SwitchBtnButton;
				entity.ShowMessage = model.ShowMessage;
				entity.WorkerId = model.WorkerId;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysMessageModel model)
        {
            try
            {
                SysMessage entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.CreateTime = model.CreateTime;
				entity.ModificationTime = model.ModificationTime;
				entity.CreateUserName = model.CreateUserName;
				entity.ModificationUserName = model.ModificationUserName;
				entity.SortCode = model.SortCode;
				entity.ParentId = model.ParentId;
				entity.BusinessID = model.BusinessID;
				entity.BusinessTable = model.BusinessTable;
				entity.PK_App_Customer_CustomerName = model.PK_App_Customer_CustomerName;
				entity.SwitchBtnRead = model.SwitchBtnRead;
				entity.Title = model.Title;
				entity.Content = model.Content;
				entity.EnumMessageType = model.EnumMessageType;
				entity.SwitchBtnButton = model.SwitchBtnButton;
				entity.ShowMessage = model.ShowMessage;
				entity.WorkerId = model.WorkerId;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysMessageModel GetById(string id)
        {
            if (IsExists(id))
            {
                SysMessage entity = m_Rep.GetById(id);
                SysMessageModel model = new SysMessageModel();
                              				model.Id = entity.Id;
				model.CreateTime = entity.CreateTime;
				model.ModificationTime = entity.ModificationTime;
				model.CreateUserName = entity.CreateUserName;
				model.ModificationUserName = entity.ModificationUserName;
				model.SortCode = entity.SortCode;
				model.ParentId = entity.ParentId;
				model.BusinessID = entity.BusinessID;
				model.BusinessTable = entity.BusinessTable;
				model.PK_App_Customer_CustomerName = entity.PK_App_Customer_CustomerName;
				model.SwitchBtnRead = entity.SwitchBtnRead;
				model.Title = entity.Title;
				model.Content = entity.Content;
				model.EnumMessageType = entity.EnumMessageType;
				model.SwitchBtnButton = entity.SwitchBtnButton;
				model.ShowMessage = entity.ShowMessage;
				model.WorkerId = entity.WorkerId;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
