//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.App
{
	public class Virtual_App_RequirementModel
	{
			public virtual string Id { get; set; }
			public virtual System.DateTime CreateTime { get; set; }
			public virtual System.DateTime ModificationTime { get; set; }
			public virtual string CreateUserName { get; set; }
			public virtual string ModificationUserName { get; set; }
			public virtual int SortCode { get; set; }
			public virtual string ParentId { get; set; }
			public virtual string Title { get; set; }
			public virtual string SubTitle { get; set; }
			public virtual string PK_App_Position_Name { get; set; }
			public virtual string WorkPlace { get; set; }
			public virtual string WorkLimitSex { get; set; }
			public virtual int WorkLimitAgeLow { get; set; }
			public virtual int WorkLimitAgeHigh { get; set; }
			public virtual string EnumWorkLimitDegree { get; set; }
			public virtual string SalaryLow { get; set; }
			public virtual string SalaryHigh { get; set; }
			public virtual string PromiseMoney { get; set; }
			public virtual string ServiceMoney { get; set; }
			public virtual string TotalServiceMoney { get; set; }
			public virtual string PublishDate { get; set; }
			public virtual int TotalHire { get; set; }
			public virtual string Tag { get; set; }
			public virtual string PK_App_Customer_CustomerName { get; set; }
			public virtual string Description { get; set; }
			public virtual string SwitchBtnRecommend { get; set; }
			public virtual string CompanyName { get; set; }
			public virtual string PK_App_Country_Name { get; set; }
			public virtual int TotalYear { get; set; }
			public virtual string TransactProvince { get; set; }
			public virtual int ApplyCount { get; set; }
			public virtual string ServiceTailMoney { get; set; }
			public virtual string SwitchBtnOpen { get; set; }
			public virtual int ClickNumber { get; set; }
			public virtual string PreTaxSalary { get; set; }
			public virtual string WorkHourPerWeek { get; set; }
			public virtual string EnumWorkPermit { get; set; }
		}
}
