//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.App
{
	public class Virtual_App_CustomerJobIntensionModel
	{
			public virtual string Id { get; set; }
			public virtual System.DateTime CreateTime { get; set; }
			public virtual System.DateTime ModificationTime { get; set; }
			public virtual string CreateUserName { get; set; }
			public virtual string ModificationUserName { get; set; }
			public virtual int SortCode { get; set; }
			public virtual string ParentId { get; set; }
			public virtual string PK_App_Customer_CustomerName { get; set; }
			public virtual string EnumPositionType { get; set; }
			public virtual string ExpectSalary { get; set; }
			public virtual string ExpectCountry { get; set; }
			public virtual string Skills { get; set; }
			public virtual string Intention { get; set; }
			public virtual string EnumApplyWay { get; set; }
			public virtual string CurrentPlace { get; set; }
			public virtual string EnumForeignLangGrade { get; set; }
			public virtual string AbroadExp { get; set; }
		}
}
