//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.App
{
	public class Virtual_App_CustomerModel
	{
			public virtual string Id { get; set; }
			public virtual System.DateTime CreateTime { get; set; }
			public virtual System.DateTime ModificationTime { get; set; }
			public virtual string CreateUserName { get; set; }
			public virtual string ModificationUserName { get; set; }
			public virtual int SortCode { get; set; }
			public virtual string ParentId { get; set; }
			public virtual Nullable<int> Record { get; set; }
			public virtual string Info { get; set; }
			public virtual string EnumCustomerLevel { get; set; }
			public virtual string CustomerName { get; set; }
			public virtual string Password { get; set; }
			public virtual string Sex { get; set; }
			public virtual string Phone { get; set; }
			public virtual string NickName { get; set; }
			public virtual int Age { get; set; }
			public virtual string Height { get; set; }
			public virtual string Weight { get; set; }
			public virtual string Nation { get; set; }
			public virtual string Introduction { get; set; }
			public virtual string CustomerPhoto { get; set; }
			public virtual string OpenID { get; set; }
			public virtual string BirthDay { get; set; }
			public virtual string BirthPlace { get; set; }
			public virtual string CurrentPlace { get; set; }
			public virtual string WeChatNumber { get; set; }
			public virtual string Cultural { get; set; }
			public virtual string EnumCustomerType { get; set; }
			public virtual string EnumForeignLangGrade { get; set; }
			public virtual string SwitchBtnPassport { get; set; }
			public virtual string AbroadExp { get; set; }
			public virtual string EnumDriverLicence { get; set; }
			public virtual string SwitchBtnRecommend { get; set; }
			public virtual string VideoPath { get; set; }
			public virtual string WordPath { get; set; }
			public virtual string WordName { get; set; }
			public virtual string WordExt { get; set; }
			public virtual string JobIntension { get; set; }
		}
}
