//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.App
{
	public class Virtual_App_OfficeModel
	{
			public virtual string Id { get; set; }
			public virtual System.DateTime CreateTime { get; set; }
			public virtual System.DateTime ModificationTime { get; set; }
			public virtual string CreateUserName { get; set; }
			public virtual string ModificationUserName { get; set; }
			public virtual int SortCode { get; set; }
			public virtual string ParentId { get; set; }
			public virtual string Tel { get; set; }
			public virtual string OfficeName { get; set; }
			public virtual string Longitude { get; set; }
			public virtual string Latitude { get; set; }
			public virtual string ContactName { get; set; }
			public virtual string ContactPhone { get; set; }
			public virtual string ContactWeChat { get; set; }
			public virtual string ContactMail { get; set; }
			public virtual string OfficeAddress { get; set; }
		}
}
